modLoader = "javafml"
loaderVersion = "[1,)"
license = "LGPL-v3"

[[mods]]
modId = "animatica"
version = "${version}"
displayName = "AnimaticaReforged"
authors = "TeamPotato"
description = '''
A Minecraft Mod.
'''

[[mixins]]
config = "animatica.mixins.json"