modLoader = "javafml"
loaderVersion = "[36,)"
license = "LGPL-v3"

[[mods]]
modId = "animatica"
version = "${version}"
displayName = "AnimaticaReforged"
authors="TeamPotato"
logoFile= "icon.png"
description = '''

'''